apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: 042749349083.dkr.ecr.ap-south-1.amazonaws.com/calculator-app-repo/latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-app
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
